export const iconNames = [
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "cart",
  "close",
  "copy",
  "external-link",
  "facebook",
  "help",
  "info",
  "instagram",
  "location",
  "navigate-back",
  "navigate-forward",
  "newsletter",
  "notification",
  "pinterest",
  "play",
  "printer",
  "reiskoch-logo",
  "restaurant",
  "rss",
  "search",
  "speaker",
  "translation",
];

export type IconName = (typeof iconNames)[number];
